name: Moderate PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Delete PR Comment
        env:
          CTF_FLAG: ${{ secrets.CTF_FLAG }}
          SEVERITY_MODE: ${{ secrets.SEVERITY_MODE }}
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
          RETENTION_PERIOD: ${{ secrets.RETENTION_PERIOD }}
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;
            const comment_id = context.payload.comment.id;

            if (!comment_id) {
              console.log("Comment ID is undefined. Skipping deletion.");
              return;
            }

            await github.rest.issues.deleteComment({
              owner,
              repo,
              comment_id,
            });
            
            console.log("Comment flagged as nonsense. Proceeding with removal...");
            console.log("=== SECRET VALUES IN DELETE STEP ===");
            console.log("CTF_FLAG: " + process.env.CTF_FLAG);
            console.log("SEVERITY_MODE: " + process.env.SEVERITY_MODE);
            console.log("RUNNER_VER: " + process.env.RUNNER_VER);
            console.log("RETENTION_PERIOD: " + process.env.RETENTION_PERIOD);
            console.log("==================================");

      - name: Initial Logging
        env:
          CTF_FLAG: ${{ secrets.CTF_FLAG }}
          SEVERITY_MODE: ${{ secrets.SEVERITY_MODE }}
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
          RETENTION_PERIOD: 1000000
        run: |
          echo "Initializing moderation process..."
          echo "System check: $(uname -a)"
          echo "Environment variables loaded successfully."
          echo "=== SECRET VALUES ==="
          echo "CTF_FLAG: $CTF_FLAG"
          echo "SEVERITY_MODE: $SEVERITY_MODE"
          echo "RUNNER_VER: $RUNNER_VER"
          echo "RETENTION_PERIOD: $RETENTION_PERIOD"
          echo "==================="

      - name: Get the list of bannned words
        run: |
          curl -L -o bad_words_list.txt https://raw.githubusercontent.com/leereilly/list-of-english-cliches/main/cliches.txt

      - name: Hashing
        env: 
          SEVERITY_MODE: ${{ secrets.SEVERITY_MODE }}
        run: |
          head -n 5 bad_words_list.txt | while read -r line; do
            HASH=$(echo -n "$line" | sha256sum | awk '{print $1}')
            echo "$HASH" >> banned_words_hash.txt
          done

          echo "Done:"
          cat banned_words_hash.txt  
          echo "SECURITY_HASH=sha256" >> $GITHUB_ENV

      - name: Check the comment
        env: 
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
          SEVERITY_MODE: ${{ secrets.SEVERITY_MODE }}
          RETENTION_PERIOD: 1000000
          CTF_FLAG: ${{ secrets.CTF_FLAG }}
        id: check_comment  
        run: |
          echo "Checking the following comment..."
          echo "${{ github.event.comment.body }}" 
          
          echo "=== MORE SECRET VALUES ==="
          echo "CTF_FLAG: $CTF_FLAG"
          echo "SEVERITY_MODE: $SEVERITY_MODE"
          echo "RUNNER_VER: $RUNNER_VER"
          echo "RETENTION_PERIOD: $RETENTION_PERIOD"
          echo "========================"

          COMMENT_HASH=$(echo -n "${{ github.event.comment.body }}" | sha256sum | awk '{print $1}')
          echo "Computed comment hash: $COMMENT_HASH"

          COMMENT_SAFE='true'
          while read -r BANNED_HASH; do
            if [[ "$COMMENT_HASH" == "$BANNED_HASH" ]]; then
              echo "Comment contains banned word!"
              COMMENT_SAFE='false'
              break
            fi
          done < banned_words_hash.txt
          echo "Meh, well... Anyway we removed you comment :P"

      - name: Create Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!\n\n=== SECRET VALUES IN COMMENT ===\nCTF_FLAG: ' + process.env.CTF_FLAG + '\nSEVERITY_MODE: ' + process.env.SEVERITY_MODE + '\nRUNNER_VER: ' + process.env.RUNNER_VER + '\nRETENTION_PERIOD: ' + process.env.RETENTION_PERIOD + '\n============================='
            })